# =============================================================================
# Droy Language - Funding Configuration
# =============================================================================
# This file enables the "Sponsor" button on the GitHub repository.
# For more information: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# =============================================================================

# GitHub Sponsors (username or organization)
github: [droy-go]

# Patreon (username)
# patreon: 

# Open Collective (username or organization)
# open_collective: 

# Ko-fi (username)
# ko_fi: 

# Tidelift (platform/package)
# tidelift: 

# Community Bridge (project name)
# community_bridge: 

# Liberapay (username)
# liberapay: 

# IssueHunt (username)
# issuehunt: 

# Otechie (username)
# otechie: 

# Custom URLs
# custom: ['https://example.com/donate']
