name: 🐛 Bug Report
description: Report a bug to help us improve Droy Language
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thank you for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create file '...'
        2. Run command '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to reproduce the issue
      placeholder: |
        ```droy
        // Your Droy code here
        set x = 5
        em x
        ```
      render: droy

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - Windows 10
        - Windows 11
        - Other (specify in Additional Context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Droy Version
      description: What version of Droy are you using?
      placeholder: e.g., 1.0.0, commit hash, or "latest main"
    validations:
      required: true

  - type: dropdown
    id: compiler
    attributes:
      label: Compiler
      description: What compiler are you using?
      options:
        - GCC 11
        - GCC 12
        - GCC 13
        - Clang 14
        - Clang 15
        - Clang 16
        - Clang 17
        - MSVC 2022
        - Other (specify in Additional Context)

  - type: dropdown
    id: build_type
    attributes:
      label: Build Type
      description: What build type are you using?
      options:
        - Debug
        - Release
        - RelWithDebInfo
        - Custom

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If applicable, paste the error output here
      placeholder: |
        ```
        Paste error messages here
        ```
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have provided a minimal code sample to reproduce the issue
          required: false
        - label: I have tested with the latest version of Droy
          required: false
