name: ❓ Question / Support
description: Ask a question or request help with Droy Language
title: "[QUESTION] "
labels: ["question", "support"]
body:
  - type: markdown
    attributes:
      value: |
        ## ❓ Question / Support
        Have a question about Droy Language? Need help with something? Ask away!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Describe your question in detail...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question
      placeholder: |
        - What are you trying to achieve?
        - What have you tried so far?
        - What documentation have you read?

  - type: textarea
    id: code
    attributes:
      label: Code Example (if applicable)
      description: If your question involves code, please provide a minimal example
      placeholder: |
        ```droy
        // Your code here
        ```
      render: droy

  - type: dropdown
    id: topic
    attributes:
      label: Topic Area
      description: What area does your question relate to?
      options:
        - Getting Started / Installation
        - Language Syntax
        - Standard Library
        - Compiler Usage
        - LLVM Backend
        - Performance
        - Debugging
        - Contributing
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm the following
      options:
        - label: I have read the documentation (README, docs/)
          required: true
        - label: I have searched existing issues for similar questions
          required: true
